### ISSUE TITLE
continuumio/miniconda3 为什么很久没更新？？？何解？

### ISSUE THREAD

**Issue by phpmac** [anaconda/docker-images#573]
continuumio/miniconda3 为什么很久没更新？？？何解？

**Comment by marcoesters** [comment]
Thanks for filing the issue - the Docker images are updated with each Miniconda release. Since there hasn't been a new Miniconda until yesterday, there hasn't been a new release of the `continuumio/miniconda3` image.

Miniconda 24.9.2 is now available on Docker, so I'll be closing this.
